{{/*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
Return the proper OpenLDAP image name
*/}}
{{- define "openldap.image" -}}
{{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
{{- end -}}

{{/*
Return the proper Docker Image Registry Secret Names
*/}}
{{- define "openldap.imagePullSecrets" -}}
{{- include "common.images.renderPullSecrets" (dict "images" (list .Values.image) "context" $) -}}
{{- end -}}

{{/*
Create the name of the service account to use
*/}}
{{- define "openldap.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
    {{ default (include "common.names.fullname" .) .Values.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}

{{/*
Return the name of the headless service
*/}}
{{- define "openldap.headlessServiceName" -}}
{{- printf "%s-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Return the name of the secret holding the OpenLDAP credentials
*/}}
{{- define "openldap.secretName" -}}
{{- if .Values.auth.existingSecret -}}
    {{- tpl .Values.auth.existingSecret $ -}}
{{- else -}}
    {{- include "common.names.fullname" . -}}
{{- end -}}
{{- end -}}

{{/*
Return true if a secret object should be created for the OpenLDAP credentials
*/}}
{{- define "openldap.createSecret" -}}
{{- if not .Values.auth.existingSecret -}}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Return the name of the secret holding the TLS certificates
*/}}
{{- define "openldap.tlsSecretName" -}}
{{- if .Values.tls.existingSecret -}}
    {{- tpl .Values.tls.existingSecret $ -}}
{{- else -}}
    {{- printf "%s-crt" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Return true if a TLS secret object should be created
*/}}
{{- define "openldap.createTlsSecret" -}}
{{- if and .Values.tls.enabled .Values.tls.autoGenerated (not .Values.tls.existingSecret) -}}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Return the name of the ConfigMap holding the custom LDIF files
*/}}
{{- define "openldap.customLdifConfigMapName" -}}
{{- if .Values.existingCustomLdifConfigMap -}}
    {{- tpl .Values.existingCustomLdifConfigMap $ -}}
{{- else -}}
    {{- printf "%s-ldifs" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Return the name of the ConfigMap holding the custom schema files
*/}}
{{- define "openldap.customSchemaConfigMapName" -}}
{{- if .Values.existingCustomSchemaConfigMap -}}
    {{- tpl .Values.existingCustomSchemaConfigMap $ -}}
{{- else -}}
    {{- printf "%s-schemas" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Return true if custom LDIF files are provided
*/}}
{{- define "openldap.hasCustomLdifs" -}}
{{- if or .Values.customLdifFiles .Values.existingCustomLdifConfigMap -}}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Return true if custom schema files are provided
*/}}
{{- define "openldap.hasCustomSchemas" -}}
{{- if or .Values.customSchemaFiles .Values.existingCustomSchemaConfigMap -}}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Return true if the PROXY protocol LDAP listener has its own port
*/}}
{{- define "openldap.exposePldap" -}}
{{- if and .Values.ldap.proxyProtocol.enabled (ne (int .Values.ldap.proxyProtocol.ldapPort) (int .Values.containerPorts.ldap)) -}}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Return true if the PROXY protocol LDAPS listener has its own port
*/}}
{{- define "openldap.exposePldaps" -}}
{{- if and .Values.tls.enabled .Values.ldap.proxyProtocol.enabled (ne (int .Values.ldap.proxyProtocol.ldapsPort) (int .Values.containerPorts.ldaps)) -}}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Render a boolean as the "yes"/"no" strings expected by the image
*/}}
{{- define "openldap.yesno" -}}
{{- if . -}}yes{{- else -}}no{{- end -}}
{{- end -}}

{{/*
Compile all warnings into a single message.
*/}}
{{- define "openldap.validateValues" -}}
{{- $messages := list -}}
{{- $messages := append $messages (include "openldap.validateValues.userPasswords" .) -}}
{{- $messages := append $messages (include "openldap.validateValues.existingClaim" .) -}}
{{- $messages := append $messages (include "openldap.validateValues.tls" .) -}}
{{- $messages := without $messages "" -}}
{{- $message := join "\n" $messages -}}

{{- if $message -}}
{{-   printf "\nVALUES VALIDATION:\n%s" $message | fail -}}
{{- end -}}
{{- end -}}

{{/*
Validate values of OpenLDAP - the number of passwords must match the number of users
*/}}
{{- define "openldap.validateValues.userPasswords" -}}
{{- if and .Values.auth.passwords (ne (len .Values.auth.passwords) (len .Values.auth.users)) -}}
openldap: auth.passwords
    The number of passwords ({{ len .Values.auth.passwords }}) must match the number of users ({{ len .Values.auth.users }}).
{{- end -}}
{{- end -}}

{{/*
Validate values of OpenLDAP - an existing claim can only be used by a single replica
*/}}
{{- define "openldap.validateValues.existingClaim" -}}
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim (gt (int .Values.replicaCount) 1) -}}
openldap: persistence.existingClaim
    An existing claim cannot be shared between several replicas. Set replicaCount=1 or unset persistence.existingClaim.
{{- end -}}
{{- end -}}

{{/*
Validate values of OpenLDAP - TLS requires a certificate source
*/}}
{{- define "openldap.validateValues.tls" -}}
{{- if and .Values.tls.enabled (not .Values.tls.autoGenerated) (not .Values.tls.existingSecret) -}}
openldap: tls.existingSecret
    TLS is enabled but no certificate is available. Set tls.existingSecret or tls.autoGenerated=true.
{{- end -}}
{{- end -}}
