{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "openldap.createSecret" .) }}
{{- $secretName := include "common.names.fullname" . }}
{{- $userPasswords := "" }}
{{- $existing := (lookup "v1" "Secret" (include "common.names.namespace" .) $secretName).data }}
{{- if .Values.auth.passwords }}
  {{- $userPasswords = join "," .Values.auth.passwords }}
{{- else if and $existing (hasKey $existing .Values.auth.secretKeys.userPasswordsKey) }}
  {{- $userPasswords = index $existing .Values.auth.secretKeys.userPasswordsKey | b64dec }}
{{- else }}
  {{- $generated := list }}
  {{- range .Values.auth.users }}
    {{- $generated = append $generated (randAlphaNum 10) }}
  {{- end }}
  {{- $userPasswords = join "," $generated }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.adminPasswordKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" .Values.auth.secretKeys.adminPasswordKey "providedValues" (list "auth.adminPassword") "length" 16 "context" $) }}
  {{ .Values.auth.secretKeys.configAdminPasswordKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" .Values.auth.secretKeys.configAdminPasswordKey "providedValues" (list "auth.configAdminPassword") "length" 16 "failOnNew" false "context" $) }}
  {{ .Values.auth.secretKeys.accesslogAdminPasswordKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" .Values.auth.secretKeys.accesslogAdminPasswordKey "providedValues" (list "ldap.accesslog.adminPassword") "length" 16 "failOnNew" false "context" $) }}
  {{ .Values.auth.secretKeys.userPasswordsKey }}: {{ $userPasswords | b64enc | quote }}
{{- end }}
